apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop # dont forget to mention this.
  #labels in service are used to filter service based on labels . 
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 27017 # this is source(service) port
      targetPort: 27017 # container port