apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop # dont forget to mention this.
  #labels in service are used to filter service based on labels . 
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 6379 # this is source(service) port
      targetPort: 6379 # container port