apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace:  roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database # has to match .spec.template.metadata.labels
  serviceName: "redis-headless" # this should be the headless service name because statefulset requires headless service to communicate to pods directly without clusterIp
  replicas: {{ .Values.StatefulSet.Spec.replicas }} # by default is 1
  template:
    metadata:
      labels:
        component: redis
        project: roboshop
        tier: database  # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: "{{ .Values.StatefulSet.Spec.imageURL }}:{{ .Values.StatefulSet.Spec.imageVersion }}"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      # this is pvc created directly in statfulset resource itself
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi